apiVersion: k8s.bitwarden.com/v1
kind: BitwardenSecret
metadata:
  labels:
    app.kubernetes.io/name: bitwardensecret
    app.kubernetes.io/instance: bitwardensecret-sample
    app.kubernetes.io/part-of: sm-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: sm-operator
  name: renovate-secret
  namespace: renovate
spec:
  organizationId: "a0846fa1-1734-467d-b98b-b179010eb3f7"
  secretName: renovate-env
  map:
    - bwSecretId: "7c38259a-0f04-4e34-a392-b1b200b046f7"
      secretKeyName: "RENOVATE_GITHUB_COM_TOKEN"
    - bwSecretId: "c689290a-7768-4dd1-bf03-b1b200b107be"
      secretKeyName: "RENOVATE_RENOVATE_AUTODISCOVER"
    - bwSecretId: "a090e646-7213-48e3-a9a4-b1b200b120b6"
      secretKeyName: "RENOVATE_RENOVATE_GIT_AUTHOR"
    - bwSecretId: "408dc10c-a1c1-4892-887f-b1b200b12ddf"
      secretKeyName: "RENOVATE_RENOVATE_PLATFORM"
  authToken:
    secretName: bw-auth-token
    secretKey: token