apiVersion: k8s.bitwarden.com/v1
kind: BitwardenSecret
metadata:
  labels:
    app.kubernetes.io/name: bitwardensecret
    app.kubernetes.io/instance: bitwardensecret-sample
    app.kubernetes.io/part-of: sm-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: sm-operator
  name: renovate-secret
  namespace: renovate
spec:
  organizationId: "a0846fa1-1734-467d-b98b-b179010eb3f7"
  secretRef:
    name: renovate-env  # This is the name of the Kubernetes secret to be created
  type: Opaque
  data:
    GITHUB_COM_TOKEN: {bwItem: "7c38259a-0f04-4e34-a392-b1b200b046f7", field: "RENOVATE_GITHUB_COM_TOKEN"}
    RENOVATE_AUTODISCOVER: {bwItem: "c689290a-7768-4dd1-bf03-b1b200b107be", field: "RENOVATE_RENOVATE_AUTODISCOVER"}
    RENOVATE_GIT_AUTHOR: {bwItem: "a090e646-7213-48e3-a9a4-b1b200b120b6", field: "RENOVATE_RENOVATE_GIT_AUTHOR"}
    RENOVATE_PLATFORM: {bwItem: "408dc10c-a1c1-4892-887f-b1b200b12ddf", field: "RENOVATE_RENOVATE_PLATFORM"}