apiVersion: k8s.bitwarden.com/v1
kind: BitwardenSecret
metadata:
  labels:
    app.kubernetes.io/name: bitwardensecret
    app.kubernetes.io/instance: bitwardensecret-sample
    app.kubernetes.io/part-of: sm-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: sm-operator
  name: bitwardensecret-sample
  namespace: bitwarden
spec:
  organizationId: "a0846fa1-1734-467d-b98b-b179010eb3f7"
  secretName: bw-sample-secret
  map:
    - bwSecretId: 2cb30740-8f68-4a90-ad05-b1a900d257cd
      secretKeyName: test__secret__1
    - bwSecretId: fa31df73-f52b-4323-9677-b1a900d25b27
      secretKeyName: test__secret__2
  authToken:
    secretName: bw-auth-token
    secretKey: token
