apiVersion: apps/v1
kind: Deployment
metadata:
  name: secret-printer
  namespace: bitwarden
spec:
  replicas: 1
  selector:
    matchLabels:
      app: secret-printer
  template:
    metadata:
      labels:
        app: secret-printer
    spec:
      containers:
      - name: secret-printer
        image: alpine
        command: ["/bin/sh"]
        args: ["-c", "echo 'Secret 1: '$TEST_SECRET_1'; Secret 2: '$TEST_SECRET_2 && sleep 3600"]
        env:
        - name: TEST_SECRET_1
          valueFrom:
            secretKeyRef:
              name: bw-sample-secret
              key: test__secret__1
        - name: TEST_SECRET_2
          valueFrom:
            secretKeyRef:
              name: bw-sample-secret
              key: test__secret__2
