---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: uptime-kuma-config
  namespace: observability
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: csi-sc-cinder
  resources:
    requests:
      storage: 1Gi
