apiVersion: v1
data:
    mariadb-database: ENC[AES256_GCM,data:d7dhkbwNVsM=,iv:Ydmt73ntaCKRej2nGH5uw4HA9xdCtGESH1irkuK64b4=,tag:KGhNftYlE9foIu3pDKq7cg==,type:str]
    mariadb-password: ENC[AES256_GCM,data:ZEmPt6LUm8JNX/0RCpz11JRMSf6xh+1P2hX7reuXMv2REGN1g47SSkc7W3Q=,iv:TmDGTk3ASnQJTvYsywZgWH4t2HJXbo2s5aJ5aOO9l3c=,tag:WwEx/XuQAxDNlZdbasi7Cw==,type:str]
    mariadb-root-password: ENC[AES256_GCM,data:rLsG2nujHCqJW6bN/inLzZCpx19W8KqxrhsWLUiIvKOvU4y20qpXOnu19i0=,iv:7/geVnR2MWb00NRQgUfjT6VSPnSXhZ7uZk65ZpdQl8k=,tag:+b5syCMICuow8k2QjsNBAA==,type:str]
    mariadb-user: ENC[AES256_GCM,data:TxKUy5RqIqQ=,iv:uwxKVw3u9r5443UHwsAoBrZq4pfk6y6hXG2Go86QPJ8=,tag:AO9xpYOuWi2EimYrz4xXwA==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: db-secrets
    namespace: familie
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-06-11T10:29:48Z"
    mac: ENC[AES256_GCM,data:HlKmWAXWt/5sTDt9CJUiytBWRlYDGNQSetgDh2vfgJ9jP51iqRTlWaFwRtCSUACXrdJ5pki2VfW/EajJ+XP0OMmA7qD/di15q9nXCwhhRRQPNWYnWRqs2Yf8Ld4sYkjCljU85sCPNcdrI2YGDbKRxve5SJ2XGT0sXDYqxDEBH9c=,iv:AU+h3FYQ8Li3o/01C4MDGeBcD53Ka775KEM0HE3DEWg=,tag:ycYHki9nGYKF22WjiUnxSg==,type:str]
    pgp:
        - created_at: "2024-06-11T10:29:48Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA2Pe/OXT8OjaAQ//VUTVDmhUYfo/QHPScZrb8LjwWyCaTJkRkdMI646ALy6L
            aIq/ZEkT51HZYPqKo0M+uGEjmUkz/WJbfJ31EcmsM6qvSsFUR61bpdz2OI7SdTuX
            ZEuekwnMqBNnnVydiYWi2pt1KPjQtkXcyOnuTCOmBieeY+xgeDtV+yp0J5HjRNdN
            nAD4QHaKtEoSEImnhDFN3yAa535RFI28QOi6s5dh1tUWjxIzllpHFJZicU602OPa
            RLV+LJOxV3Kgv6F2o2gGs1ON0XmOaPgeHe7QqE5w62RX65DLo9t25Kq3lu+4bUoN
            oEXdM7g449cYtrlf7nVtZkNwJ7n+93XqbegYmxmc40GP/QYPZGKYm04hY2tB8Y0l
            J/l8wJLqjCdtxS+dnpyDlBNaVab4YaQl+YGsHeL13HR3hjOvIDqAmZHqQlBV+1XK
            NPWvZlsXxCWdRb9bGn0//RAl6Gb83dUROEdtMFM8Kqv0MQS4plZPsWsqInVd3xfq
            yE1jM3A8OZiUzqIIlfYz0of0Iv3VF2p63n+LaCqF5zWxfEY+gIgiMQNpE2yvYpBP
            /I9/yqbzbIhazg6AwvJoyODveCoLfJEtQlhyLmdp9dxoIJdbYgKoRSjBw1X68nKn
            f+2Pi81r/LudiVnaB//5hzVh4/qDff9oHiAg5sMCDR4R0JnUDk1/2Da741KibAbU
            aAEJAhBVRYLxoFo1y8PBwihV+NECu86rV7HwSi2YN1ynYJPSGUlOP2o/6jdVIASf
            0ArxiDTTGb/NugxtKpT9vHlsxniAP3CtkItM4LvreOPbrL6FqKNdBj8NESxCSguF
            Z3O0XVqrOPoC
            =MINw
            -----END PGP MESSAGE-----
          fp: 9CC20C77F3F6B67B71EF359DA806117AFCA37F64
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
