apiVersion: v1
data:
    auth.database: ENC[AES256_GCM,data:npdGHhD1Zj4=,iv:LnnaZdG5wxsMFANEQHMkbhf1hbHDZMxDdQ56L9GjmK4=,tag:F9vxMSsNTilkMmuRClq2FQ==,type:str]
    auth.password: ENC[AES256_GCM,data:LV4/Z6AMrTTSYYCYpky9MOs6ZBiGZr0buBlUKg6ovN/By3GXgNuTFNWgG9s=,iv:/gk9S/YsOW67biaYzTm21vegZit/h8RE5+iyD7j1l94=,tag:OLSaBlpbR7oc7oJ0jJVyGw==,type:str]
    auth.rootPassword: ENC[AES256_GCM,data:rNeVNzUvfGbWKgMqi0v2FQx2jnBIqLbRkEvBvnhoQxCFxkPiLieKGNmAGHg=,iv:xfRt25WFkwbPYoX937HLnAVoa/f0GpFOvtD2926ybgA=,tag:wgvx4T73YZmV6vg8uyzXUA==,type:str]
    auth.username: ENC[AES256_GCM,data:PIJ0c4gphfI=,iv:mpQirH412+pIm6Fp9LR11eYPydDOLVQZkSlbEpLYNYU=,tag:VlfwSKu6vmk1eCH7pWR+2g==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: db-secrets
    namespace: familie
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-06-11T10:26:18Z"
    mac: ENC[AES256_GCM,data:xbh19XeNP1JNQ9fqiyX7KaPLMHD7BUtNWqwJhdgs+nowxp2zjPgqji8E/ndMQm47lQgPJddHlGYbJNXTbauLbIgkBymwgecWE3uR3u/J7NT7/NwdcmvTolN+52GF4Ml3C21amPEeJZcBRD5KtvunW5sB/oNevwF9A52ufU8fRQA=,iv:MZ9P9xiRoCs5VVgDqX51i9GkmmW/bZfG6TvcpuCEWgA=,tag:QQfM2yDmxI9PtZdK2mAB9w==,type:str]
    pgp:
        - created_at: "2024-06-11T10:26:18Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA2Pe/OXT8OjaAQ/+ING1HF+nP8huJChakwhlwftuUNrWyzdcZqr+AFce4dMo
            y5QyOL9S1L67SSFsB8azVKdIkPP1t4SGSHAkFaLFKVbtxbpAUA/5YjKVe2ohrUiZ
            ip/DKk0/mszcODObJI5pcn8RmA8Q5gw8NnnxB8lVVesc7kvzh8xvYTN4HNjH7eNp
            Z3YE+z24EkVOO9s9RShBLKXETP/PR0HSRJ41pJTzHi445p8UNrip8HNYNo1BB+Ev
            2T7X4jYUK5q+yZkW/i1S/e4Y7q0UzJZEoO0ASHZxx9CpnDCsdPx/D4jmQ0wYKfLG
            Bqtgs0cRwAGSRnfmAhbF+RX+MnUsx4Vkp15v9nWFcOLCwPkZS4ojmahiNlkVu6bp
            VB1h5wq3SmkQRrwuCu3Y4CACtW1zrLeoJwF+1wArS2gDiy3J1jQl8UUyZfq6Qo4b
            jUY8zZ8JeSxkiLDrG/jgrQPH4S4+N6yjyHXCzQ0AYWakdx6zkQCpa3mbJf8R/b6t
            RKWalfHR5Ic37HTAJFe1oGHiWpUlTeiPKGDONuDJ0+/g9n4RJMbWAoMdiiOaHOCa
            sV+Xz23Xh+9bgkmYXaK7wPBlJqDFtPIcnAhfiVE4sNTJI1qf1/JkgGQ5iNa4FaBu
            gx+Iln3OOJNwV1LT7Xu+DFotBCXzxQIa20bDLWhhRGQZ98j20d1xE3bBZDT4WqzU
            aAEJAhBsGGirT9fSrVEbJhql9JufUEL3AYukAzINaC+c4/iBREEx77GGPbFUo26U
            f95PpqXlkZ/vBNYL8D28JTOkTe31gZkTWb8S4EpDmfXE4J0Fgxv9GJnFtgkUcbrd
            RS5l0UhpCcdX
            =VZNs
            -----END PGP MESSAGE-----
          fp: 9CC20C77F3F6B67B71EF359DA806117AFCA37F64
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
