apiVersion: v1
data:
    database: ENC[AES256_GCM,data:kQMgYi9Vv1oLsSq5,iv:JVuCh5i/n382N583LIlbXtlIgmVirPSFh4HMXWnl2dw=,tag:2MlLjVNsXN9yPvfTUh79qQ==,type:str]
    password: ENC[AES256_GCM,data:UMuG+vjE35sj+deKTiKffSFjvImKvAo5gEw4yrIKd7O1U5gxwaCeWSTHyP4=,iv:HGjs2I0v708miL1zEZqUpYkKtZdT70rh9niEYPVcN9k=,tag:uVPAxZzr7Fn9gxQQn7ry5g==,type:str]
    rootPassword: ENC[AES256_GCM,data:opdrR+gCgZrnCr7O3A3bDFsTLT2PaOkSmqSSBj8EBpZ21vjB95CST7Y2Xwo=,iv:WCymOzDN1xJkh1I2pB3vBkeenWxvt82ox8D2wZOxEbM=,tag:FbBB/VK/BRN+oObrIrhynQ==,type:str]
    username: ENC[AES256_GCM,data:KhSPE7RCMeE=,iv:BKRrvhOJjRh0B+fBw4zLp4evI8simPP3dqAisA96TYo=,tag:GjFIL/fqxX7X8nI0KWoMaw==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: db-secrets
    namespace: familie
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-06-11T08:35:58Z"
    mac: ENC[AES256_GCM,data:PiQCNgmuA0D3rWfQOZvJeLBDjS+xeqj/xRcsRpOEjKbRP0r2PnTWqBNQloOg+kXuwXz4j1s2XNq6NcelpsNytuDVgeje2ipTwMu1h93weW0EFmZG3HRjoqXWSAr7s00+i55b/9S8vWsiz+RLhyAnZZrEk30OYZC00tID9k0iSZc=,iv:P7lLMK5yYvmZSGrgjPWjvulGGtMEwspzmBIsAu5CTHY=,tag:ND4Pja+DseC+umJkAK7wRw==,type:str]
    pgp:
        - created_at: "2024-06-11T08:35:58Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA2Pe/OXT8OjaAQ/+PufdYU6V2SgZDcGQAnfXexyzT6tvyp+p0R/W6lMFaoZu
            N/+j+HgRvL1/1iag0mIB7VwrRKfFSgPqGATpoQbmjhh/UvghIkD+zN+MqEdeG+qZ
            SMgrdNzhzmNdTGzymHZPt1lkCd6DSUe5V25lIxyxDZn837zL4/z6/weeVyPZfjqr
            Bv7KxAdyXEUO3C3WVzjmlO+APqA9zPtUUnZDxB/cIIGRpByyoskWd26BzrCTj6UV
            sawFC89QXM45/t8uqbGlSq9ImPwM4TLxpnTCt13OBBaMuLMCYiUy0eVCloypDaqO
            kbl2St3rhLCg10+3DUijoQGhrgLcfXykjMaKROH1gzAoapIhv2T16Y2fJlf7AzTy
            csFd+dvQr80TKacDRFiw3QViqw9ACAm7yPU00DVcyn9YHbvz9D/BwkT7sd+pndBW
            ck7elvu0k6ZD/UF5bAIgoVxq7BN1sM1Q940pfNfH/ajbNKOCrTmBO9Oc9MJkLI5Y
            +Vp5Syqk0IvLuLA4ZBsriyH1/b24WRxyneuQ1nbGioQJ8SiPzAhTh/iHazEeliyM
            WuY3I1R7rVPzJiHxM3ccaUXGaf0rUX2pdGHnExhoYWdTV+zOLZiaWxvr4oAOdrRW
            vdZoKjBS7PjeZc9i8hbxxlwGie280x8C8pKud0PMouGvxMu2cOPEnGQdVliBWJDU
            ZgEJAhBxnI5ebm7g4NjrbxbTNMTkcXIYqFpVTNgxde9zu/ovCPBtopHvy+Iiuqmq
            Kj38iwsVP+SopYc/NohJ2sKAEdsFTNpITugWPMhep/WtaPlagku4ydv9oWRDgonz
            UgWEh7BE4w==
            =/PQG
            -----END PGP MESSAGE-----
          fp: 9CC20C77F3F6B67B71EF359DA806117AFCA37F64
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
