apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-configmap
  namespace: default
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
    <title>Fisefint!</title>
    </head>
    <body>
    <h1>Fisefint!</h1>
    <p>Hurra!</p>
    </body>
    </html>
