apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nginx-ingress
  namespace: nginx-ingress
spec:
  interval: 5m
  chart:
    spec:
      chart: nginx-ingress
      version: 'v1.9.2'  # Check for the latest stable version
      sourceRef:
        kind: HelmRepository
        name: nginx-stable
        namespace: flux-system
      interval: 1m
  values:
    controller:
      replicaCount: 2
      metrics:
        enabled: true
    defaultBackend:
      enabled: true
