apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: bitwarden secrets manager kubernetes operator
  namespace: bitwarden
spec:
  interval: 5m
  chart:
    spec:
      chart: sm-operator
      version: '0.1.0-Beta'  # Check for the latest stable version
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx-charts
        namespace: flux-system
      interval: 1m
  values:
    controller:
      replicaCount: 3
      metrics:
        enabled: true
    defaultBackend:
      enabled: true
