apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: bitwarden-secrets-manager-kubernetes-operator
  namespace: bitwarden
spec:
  interval: 5m
  chart:
    spec:
      chart: sm-operator
      version: '0.1.0-Beta'  # This specifies the version to use, here it's a development version
      sourceRef:
        kind: HelmRepository
        name: bitwarden  # This should match the name of the HelmRepository resource you defined
        namespace: flux-system
      interval: 1m
  values:
    controller:
      replicaCount: 3
      metrics:
        enabled: true
    defaultBackend:
      enabled: true
