---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-dns-cloudflare
  namespace: external-dns
spec:
  interval: 30m
  chart:
    spec:
      chart: external-dns
      version: 1.14.4
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: flux-system
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    crds: CreateReplace
    remediation:
      strategy: rollback
      retries: 3
  values:
    fullnameOverride: external-dns-cloudflare
    provider:
      name: cloudflare
    env:
      - name: CF_API_EMAIL
        valueFrom:
          secretKeyRef:
            name: external-dns-cloudflare-secret
            key: CF_API_EMAIL
      - name: CF_API_KEY
        valueFrom:
          secretKeyRef:
            name: external-dns-cloudflare-secret
            key: CF_API_KEY
    extraArgs:
      - --cloudflare-dns-records-per-page=1000
      - --cloudflare-proxied
      - --crd-source-apiversion=externaldns.k8s.io/v1alpha1
      - --crd-source-kind=DNSEndpoint
      - --events
      - --ignore-ingress-tls-spec
      - --ingress-class=external
    policy: sync
    sources: ["crd", "ingress"]
    txtOwnerId: default
    txtPrefix: k8s.
    domainFilters: ["fyksen.me"]
    serviceMonitor:
      enabled: true
