# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Pre Flux-Kustomizations
  - ./nginx-stable.yaml
  - ./external-dns.yaml
  - ./bjw-s-charts.yaml
  - ./jetstack.yaml