# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: observability
resources:
  # Pre Flux-Kustomizations
  - ./app/persistent-volume-claim.yaml
  - ./app/namespace.yaml
  - ./app/helm-release.yaml
