---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ghost-content-pvc
  namespace: familie
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: "csi-sc-cinder"
  resources:
    requests:
      storage: 50Gi
