---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ghost-mariadb
  namespace: familie
spec:
  interval: 15m
  chart:
    spec:
      chart: mariadb
      version: 18.2.2
      sourceRef:
        kind: HelmRepository
        name: bitnami-charts
        namespace: flux-system
      interval: 15m
  values:
    auth:
      # database__connection__host: ghost-mariadb
      rootPassword: ${MEDIA_GHOST_DB_ROOT_PASSWORD}
      username: ${MEDIA_GHOST_DB_USER}
      password: ${MEDIA_GHOST_DB_PASSWORD}
      database: ${MEDIA_GHOST_DB_DB}
    persistence:
      existingClaim: ghost-db-pvc

kubectl -n familie create secret generic db-secrets \
--from-literal=rootPassword=Toipaiyun9Waovegho1oohie8chaim4l \
--from-literal=username=ghost \
--from-literal=password=ko5aefiwoongethie5dohche0ce5Mii2 \
--from-literal=database=ghost-db \
--dry-run=client -o yaml > db-secrets.yaml
