---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ghost-mariadb
  namespace: familie
spec:
  interval: 15m
  chart:
    spec:
      chart: mariadb
      version: 18.2.2
      sourceRef:
        kind: HelmRepository
        name: bitnami-charts
        namespace: flux-system
      interval: 15m
  values:
      auth:
        rootPassword: "{{ .Values.auth.rootPassword | b64enc }}"
        username: "{{ .Values.auth.username | b64enc }}"
        password: "{{ .Values.auth.password | b64enc }}"
        database: "{{ .Values.auth.database | b64enc }}"
      mariadb:
        existingSecret: db-secrets
      persistence:
        existingClaim: ghost-db-pvc
  