---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ghost
  namespace: familie
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 3.2.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
      interval: 15m
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: ghost
              tag: 5.87.3
            env:
              - name: TZ
                value: "Europe/Oslo"
              - name: url
                value: "https://ghost-test.fyksen.me"
              - name: database__client
                value: "mysql"
              - name: database__connection__database
                value: "ghost"
              - name: database__connection__user
                valueFrom:
                  secretKeyRef:
                    name: db-secrets
                    key: mariadb-user
              - name: database__connection__password
                valueFrom:
                  secretKeyRef:
                    name: db-secrets
                    key: mariadb-password
              - name: database__connection__database
                valueFrom:
                  secretKeyRef:
                    name: db-secrets
                    key: mariadb-database
              - name: database__connection__host
                value: "ghost-mariadb.familie.svc.cluster.local"                 

    service:
      main:
        controller: main
        ports:
          http:
            port: 2368
    ingress:
      main:
        enabled: true
        className: nginx
        annotations:
          nginx.ingress.kubernetes.io/proxy-body-size: 2G
        hosts:
          - host: ghost-test.fyksen.me
            paths:
              - path: "/"
                pathType: "Prefix"
                service:
                  identifier: main
                  port: http
        tls:
          - hosts:
              - ghost-test.fyksen.me
            secretName: ghost-test-fyksen-me-tls
    persistence:
      content:
        enabled: true
        globalMounts:
          - path: /var/lib/ghost/content
        existingClaim: ghost-content-pvc
