# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Pre Flux-Kustomizations
  - ./cert-manager/
  - ./em-fyksen-me/
  - ./external-dns/
  - ./nginx-ingress/
  - ./uptime-kuma/
  - ./bitwarden-so/
  - ./renovate/
#  - ./ghost/ 